const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm'),path=require('path');
function fixture({requested=false,sendError=false,updateError=false,user=true}={}){
 const nodes={},calls=[],messages=[];let onAuth;const $=id=>nodes[id]??={value:'',disabled:false,events:{},addEventListener(event,fn){this.events[event]=fn;},checkValidity(){return true;}};
 const sb={auth:{onAuthStateChange(fn){onAuth=fn;},async resetPasswordForEmail(email,options){calls.push({send:email,options});return {error:sendError?{}:null};},async getUser(){return {data:{user:user?{id:'u'}:null}};},async updateUser(body){calls.push({update:body});return {error:updateError?{}:null};},async signOut(){calls.push({logout:true});}}};
 const ctx={window:{},location:{origin:'https://app.test',replace:url=>calls.push({redirect:url})}};
 vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../web/app/account-recovery.js'),'utf8'),ctx);
 const recovery=ctx.window.SaasAccountRecovery({sb,$,show:id=>calls.push({show:id}),setMsg:(id,text,kind)=>messages.push({id,text,kind}),requested});
 return {$,calls,messages,recovery,auth:(event,session)=>onAuth(event,session),event:(id,type='submit')=>$(id).events[type]({preventDefault(){}})};
}
test('reset request uses the fixed application origin and non-enumerating response',async()=>{const f=fixture();f.$('reset-email').value='test@example.test';await f.event('reset-form');assert.equal(f.calls[0].options.redirectTo,'https://app.test/');assert.match(f.messages.at(-1).text,/Se esiste un account/);assert.equal(f.$('reset-submit').disabled,false);});
test('recovery URL alone never authorizes a password update',async()=>{const f=fixture({requested:true});await f.event('recovery-form');assert.equal(f.calls.length,0);assert.equal(f.recovery.isActive(),true);});
test('recovery event requires a valid session and matching strong password',async()=>{const f=fixture();f.auth('PASSWORD_RECOVERY',{user:{id:'u'}});f.$('new-password').value='short';f.$('confirm-password').value='short';await f.event('recovery-form');assert(!f.calls.some(c=>c.update));f.$('new-password').value='long-password-123';f.$('confirm-password').value='different-password';await f.event('recovery-form');assert(!f.calls.some(c=>c.update));});
test('successful password change clears inputs and requires signing in again',async()=>{const f=fixture();f.auth('PASSWORD_RECOVERY',{user:{id:'u'}});f.$('new-password').value=f.$('confirm-password').value='long-password-123';await f.event('recovery-form');assert(f.calls.some(c=>c.update));assert(f.calls.some(c=>c.logout));assert.equal(f.$('new-password').value,'');assert.equal(f.$('recovery-submit').disabled,true);});
test('expired session cannot update a password',async()=>{const f=fixture({user:false});f.auth('PASSWORD_RECOVERY',{user:{id:'u'}});f.$('new-password').value=f.$('confirm-password').value='long-password-123';await f.event('recovery-form');assert(!f.calls.some(c=>c.update));assert.equal(f.messages.at(-1).kind,'error');});
test('ordinary login does not open password recovery',()=>{const f=fixture();f.auth('SIGNED_IN',{user:{id:'u'}});assert.equal(f.recovery.isActive(),false);assert.equal(f.calls.length,0);});
test('provider failure is retryable and never claims password was updated',async()=>{const f=fixture({updateError:true});f.auth('PASSWORD_RECOVERY',{user:{id:'u'}});f.$('new-password').value=f.$('confirm-password').value='long-password-123';await f.event('recovery-form');assert.equal(f.messages.at(-1).kind,'error');assert(!f.calls.some(c=>c.logout));assert.equal(f.$('recovery-submit').disabled,false);});
