const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const vm=require('node:vm');
const html=fs.readFileSync(path.join(__dirname,'../web/assistente-ai.html'),'utf8');
function source(a,b){const i=html.indexOf(a),j=html.indexOf(b,i+a.length);assert.ok(i>=0&&j>i);return html.slice(i,j);}
const resolver=source('  async function resolveGenerateInvoice(a){','  // Nessuna anteprima dettagliata');
function fixture(){let current=[];const writes=[];const context={DB:{ddt:[]},companyId:'C',esc:String,findOrdine:()=>({id:'O',num:'OC-1'}),store:{loadCollection:async(type,company)=>{assert.equal(type,'ddt');assert.equal(company,'C');return current;}},window:{SaasCascade:{creaFattureDaOrdine:async(store,company,order,ddt)=>{writes.push({order,ddt});return {fatture:[{num:'FT-1'}]};}}}};vm.createContext(context);vm.runInContext(resolver,context);return {context,writes,setRows:rows=>current=rows};}
test('invoice action remains executable before DDT exists and refreshes after preceding creation',async()=>{const f=fixture();const action=await f.context.resolveGenerateInvoice({order:'OC-1'});assert.equal(typeof action.apply,'function');f.setRows([{id:'new',ocId:'O'},{id:'other',ocId:'OTHER'},{id:'cancelled',ocId:'O',annullato:true},{id:'paid',ocId:'O',ftId:'FT0'}]);assert.match(await action.apply(),/FT-1/);assert.deepEqual(Array.from(f.writes[0].ddt,d=>d.id),['new']);assert.equal(f.writes[0].order.id,'O');});
test('no eligible DDT and refresh failure produce errors with no invoice writes',async()=>{const f=fixture();const action=await f.context.resolveGenerateInvoice({order:'OC-1'});await assert.rejects(action.apply(),/Nessun DDT/);f.context.store.loadCollection=async()=>{throw Error('offline');};await assert.rejects(action.apply(),/offline/);assert.equal(f.writes.length,0);});
test('unknown order is never converted into a different entity at execution',async()=>{const f=fixture();f.context.findOrdine=()=>null;assert.equal((await f.context.resolveGenerateInvoice({order:'unknown'})).apply,null);});
test('actual action executor reports failures rather than an unconditional success',async()=>{let output;const elements={'action-confirm':{},'action-q':{value:'request'}};const context={$:id=>elements[id],ACTION_PLAN:[{apply:async()=>{throw Error('no invoice');}}],loadDB:async()=>{},actionSetOut:value=>output=value,esc:String};vm.createContext(context);vm.runInContext(source('  async function actionExecute(){',"  $('action-go').addEventListener"),context);await context.actionExecute();assert.match(output,/terminate con errori/);assert.doesNotMatch(output,/✓ Operazione completata/);assert.match(output,/no invoice/);});
