const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),vm=require('vm'),{stripTypeScriptTypes}=require('node:module');
function fixture({role='admin',customer='cus_stored',memberError=false,companyError=false,providerError=false,evilUrl=false}={}){
 let handler;const calls=[];
 const client={auth:{getUser:async()=>({data:{user:{id:'u'}},error:null})},from(table){return {select(){return this;},eq(){return this;},async maybeSingle(){return table==='memberships'?{data:role?{role}:null,error:memberError?{}:null}:{data:{stripe_customer_id:customer},error:companyError?{}:null};}};}};
 const source=fs.readFileSync(path.join(__dirname,'../supabase/functions/stripe-checkout/index.ts'),'utf8').replace(/^import .*;\r?\n/gm,'');
 vm.runInNewContext(stripTypeScriptTypes(source),{URL,URLSearchParams,Request,Response,createClient:()=>client,corsForRequest:()=>({allowed:true,headers:{}}),Deno:{env:{get:k=>k==='EDGE_ALLOWED_ORIGINS'?'https://app.test':k==='COMMERCIAL_CHECKOUT_ENABLED'?'false':'test'},serve:h=>handler=h},fetch:async(url,init)=>{calls.push({url,body:new URLSearchParams(init.body)});return Response.json(providerError?{error:{message:'private provider error'}}:{url:evilUrl?'https://evil.test/':'https://billing.stripe.com/p/session/test'},{status:providerError?500:200});}});
 return {calls,run:(body={})=>handler(new Request('https://edge.test',{method:'POST',headers:{Authorization:'Bearer test'},body:JSON.stringify({action:'portal',company_id:'company',return_url:'https://app.test/abbonamento.html',...body})}))};
}
test('portal uses the stored company customer, ignoring caller-supplied identity',async()=>{const f=fixture();const r=await f.run({customer:'cus_victim'});assert.equal(r.status,200);assert.equal(f.calls.length,1);assert.equal(f.calls[0].body.get('customer'),'cus_stored');assert(f.calls[0].url.endsWith('/billing_portal/sessions'));});
for(const role of ['operatore','viewer',null])test('portal rejects unauthorized membership '+role,async()=>{const f=fixture({role});assert.equal((await f.run()).status,403);assert.equal(f.calls.length,0);});
test('portal fails closed on membership or company query errors',async()=>{for(const options of [{memberError:true},{companyError:true}]){const f=fixture(options);assert.equal((await f.run()).status,503);assert.equal(f.calls.length,0);}});
test('portal rejects foreign return origins and credentials in URLs',async()=>{for(const return_url of ['https://evil.test/','https://user@app.test/','javascript:alert(1)']){const f=fixture();assert.equal((await f.run({return_url})).status,400);assert.equal(f.calls.length,0);}});
test('portal requires an existing billing customer',async()=>{const f=fixture({customer:null});assert.equal((await f.run()).status,409);assert.equal(f.calls.length,0);});
test('portal provider errors and unsafe URLs are not forwarded',async()=>{for(const opts of [{providerError:true},{evilUrl:true}]){const f=fixture(opts),r=await f.run();assert.equal(r.status,502);assert(!JSON.stringify(await r.json()).includes('private provider'));}});
test('new checkout is blocked while commercial prices remain undefined',async()=>{const f=fixture();const r=await f.run({action:'checkout',plan_id:'base',success_url:'https://app.test/ok',cancel_url:'https://app.test/cancel'});assert.equal(r.status,503);assert.equal(f.calls.length,0);});
