const {test,before,after}=require('node:test');const assert=require('node:assert/strict');const {database,seedTenants,asRole,uuid}=require('./helpers/database.cjs');
let db,users,companies,seq=7000;const customer=uuid(501),supplier=uuid(502),other=uuid(503);const id=()=>uuid(++seq);
before(async()=>{db=await database(37);({users,companies}=await seedTenants(db));await db.query('insert into clienti(id,company_id,nome) values($1,$2,$3),($4,$5,$6)',[customer,companies.A,'C',other,companies.B,'Other']);await db.query('insert into fornitori(id,company_id,nome) values($1,$2,$3)',[supplier,companies.A,'S']);});after(async()=>{if(db)await db.close();});
const snapshot=n=>Object.fromEntries(['id','num','data',n.cliente_id?'cliente_id':'fornitore_id','fattura_id','righe','extra'].map(k=>[k,n[k]]));
async function fixture(kind='customer'){const inv=id(),party=kind==='customer'?customer:supplier,table=kind==='customer'?'fatture_cliente':'fatture_fornitore',key=kind==='customer'?'cliente_id':'fornitore_id';await db.query(`insert into ${table}(id,company_id,num,data,${key},righe) values($1,$2,$3,$4,$5,$6)`,[inv,companies.A,'INV-'+inv,'2026-09-19',party,JSON.stringify([{qty:1,prezzo:100,iva:0}])]);return {num:kind==='customer'?null:'NCF-'+inv,data:'2026-09-19',[key]:party,fattura_id:inv,righe:[{qty:1,prezzo:40,iva:0}],extra:{note:'keep'}};}
async function save(doc,expected=null,kind='customer',request=id(),user=users.admin){return (await asRole(db,'authenticated',user,tx=>tx.query('select save_credit_note($1,$2,$3,$4,$5) result',[companies.A,kind,request,expected?JSON.stringify(expected):null,JSON.stringify(doc)]))).rows[0].result;}
async function cancel(note,kind='customer',request=id(),reason='Wrong credit',user=users.admin){return (await asRole(db,'authenticated',user,tx=>tx.query('select cancel_credit_note($1,$2,$3,$4,$5) result',[companies.A,kind,request,JSON.stringify(snapshot(note)),reason]))).rows[0].result;}
for(const kind of ['customer','supplier'])test(kind+' create update cancel and retry preserve metadata and audit',async()=>{const d=await fixture(kind),key=id();const n=await save(d,null,kind,key);assert.deepEqual(await save(d,null,kind,key),n);const edit={...snapshot(n),righe:[{qty:1,prezzo:60,iva:0}]};const updated=await save(edit,snapshot(n),kind);assert.equal(updated.extra.note,'keep');const ck=id(),c=await cancel(updated,kind,ck);assert.equal(c.extra.annullato,true);assert.deepEqual(await cancel(updated,kind,ck),c);assert.equal((await db.query('select count(*)::int n from credit_note_operations where result->>\'id\'=$1',[n.id])).rows[0].n,3);});
test('overcredit create and edit fail without changing note or consuming counter',async()=>{const d=await fixture(),n=await save(d);await assert.rejects(save({...d,righe:[{qty:1,prezzo:61,iva:0}]}),/cumulativo/);await assert.rejects(save({...snapshot(n),righe:[{qty:1,prezzo:101,iva:0}]},snapshot(n)),/cumulativo/);const n2=await save({...d,righe:[{qty:1,prezzo:60,iva:0}]});assert.equal(Number(n2.num.split('/').at(-1)),Number(n.num.split('/').at(-1))+1);});
test('CAS stale and replay payload mismatch fail',async()=>{const d=await fixture(),key=id(),n=await save(d,null,'customer',key);await assert.rejects(save({...d,extra:{changed:true}},null,'customer',key),/chiave/);await save({...snapshot(n),extra:{note:'new'}},snapshot(n));await assert.rejects(save(snapshot(n),snapshot(n)),/modificata/);});
test('roles tenant and linked party validated',async()=>{const d=await fixture();await assert.rejects(save(d,null,'customer',id(),users.viewer),/autorizzata/);await assert.rejects(save(d,null,'customer',id(),users.otherAdmin),/autorizzata/);await assert.rejects(save({...d,cliente_id:other}),/controparte/);const n=await save(d,null,'customer',id(),users.operator);await assert.rejects(cancel(n,'customer',id(),'reason',users.operator),/amministratori/);await assert.rejects(cancel(n,'customer',id(),''),/motivazione/);});
test('normal clients cannot directly insert update delete notes or inspect audit',async()=>{const n=await save(await fixture());await assert.rejects(asRole(db,'authenticated',users.admin,tx=>tx.query('update note_credito set num=$1 where id=$2',['bypass',n.id])),/transazionale/);await assert.rejects(asRole(db,'authenticated',users.admin,tx=>tx.query('delete from note_credito where id=$1',[n.id])),/transazionale/);await assert.rejects(asRole(db,'authenticated',users.admin,tx=>tx.query('select * from credit_note_operations')),/permission denied/);});
test('legacy ambiguous mutation refuses without rewriting and standalone notes remain supported',async()=>{const d=await fixture(),n=await save({...d,fattura_id:null});await db.query('update note_credito set extra=$1 where id=$2',[JSON.stringify({ftIds:['OLD1','OLD2']}),n.id]);const fresh=(await db.query('select to_jsonb(n) n from note_credito n where id=$1',[n.id])).rows[0].n;await assert.rejects(save(snapshot(fresh),snapshot(fresh)),/storico/);await assert.rejects(cancel(fresh),/storico/);});
test('audit failure rolls note and numbering back',async()=>{const d=await fixture();await db.exec("create function fail_credit_audit() returns trigger language plpgsql as $$begin raise exception 'injected failure';end$$;create trigger fail_credit_audit before insert on credit_note_operations for each row execute function fail_credit_audit();");try{await assert.rejects(save(d),/injected failure/);assert.equal((await db.query('select count(*)::int n from note_credito where fattura_id=$1',[d.fattura_id])).rows[0].n,0);}finally{await db.exec('drop trigger fail_credit_audit on credit_note_operations;drop function fail_credit_audit();');}});

test('cancel releases credit capacity and cancelled note cannot be edited',async()=>{const d=await fixture(),n=await save({...d,righe:[{qty:1,prezzo:100,iva:0}]});await assert.rejects(save(d),/cumulativo/);const cancelled=await cancel(n);await assert.rejects(save(snapshot(cancelled),snapshot(cancelled)),/annullata/);assert.ok((await save(d)).id);});
test('same tenant wrong party and immutable invoice linkage rejected',async()=>{const d=await fixture(),second=id();await db.query('insert into clienti(id,company_id,nome) values($1,$2,$3)',[second,companies.A,'Second']);await assert.rejects(save({...d,cliente_id:second}),/stessa controparte/);const n=await save(d);await assert.rejects(save({...snapshot(n),fattura_id:null},snapshot(n)),/non modificabili/);});
test('negative discounts VAT and nonpositive note totals rejected',async()=>{const d=await fixture();for(const row of [{qty:1,prezzo:1,iva:-1},{qty:1,prezzo:1,iva:0,sconto:'110'},{qty:1,prezzo:1,iva:0,sconto:'-5'},{qty:1,prezzo:0,iva:0}])await assert.rejects(save({...d,righe:[row]}),/IVA|sconto|positivo/);});
test('direct insert bypass rejected while private helper remains inaccessible',async()=>{const d=await fixture();await assert.rejects(asRole(db,'authenticated',users.admin,tx=>tx.query('insert into note_credito(company_id,num,data,cliente_id,righe) values($1,$2,$3,$4,$5)',[companies.A,'BYPASS','2026-09-19',customer,JSON.stringify(d.righe)])),/transazionale/);await assert.rejects(asRole(db,'authenticated',users.admin,tx=>tx.query('select mutate_credit_note($1,$2,$3,null,$4,$5,null)',[companies.A,'customer',id(),JSON.stringify(d),'save'])),/permission denied/);});
test('an already overcredited legacy invoice fails closed on mutation without rewriting history',async()=>{const d=await fixture();await db.query('insert into note_credito(company_id,num,data,cliente_id,fattura_id,righe) values($1,$2,$3,$4,$5,$6)',[companies.A,'LEGACY-'+id(),'2026-09-19',customer,d.fattura_id,JSON.stringify([{qty:1,prezzo:120,iva:0}])]);await assert.rejects(save(d),/cumulativo/);assert.equal((await db.query('select count(*)::int n from note_credito where fattura_id=$1',[d.fattura_id])).rows[0].n,1);});

for(const kind of ['customer','supplier'])test(kind+' invoice cannot shrink below credits, relink party or delete even after cancellation',async()=>{const d=await fixture(kind),n=await save(d,null,kind),table=kind==='customer'?'fatture_cliente':'fatture_fornitore',partyTable=kind==='customer'?'clienti':'fornitori',partyKey=kind==='customer'?'cliente_id':'fornitore_id',newParty=id();await db.query(`insert into ${partyTable}(id,company_id,nome) values($1,$2,$3)`,[newParty,companies.A,'Another']);const execute=(sql,args)=>asRole(db,'authenticated',users.admin,tx=>tx.query(sql,args));await assert.rejects(execute(`update ${table} set righe=$1 where id=$2`,[JSON.stringify([{qty:1,prezzo:39,iva:0}]),d.fattura_id]),/inferiore al credito/);await execute(`update ${table} set righe=$1 where id=$2`,[JSON.stringify([{qty:1,prezzo:40,iva:0}]),d.fattura_id]);await cancel(n,kind);await assert.rejects(execute(`update ${table} set ${partyKey}=$1 where id=$2`,[newParty,d.fattura_id]),/controparte/);await assert.rejects(execute(`delete from ${table} where id=$1`,[d.fattura_id]),/note credito/);await db.query(`delete from ${table} where id=$1`,[d.fattura_id]);});

for(const kind of ['customer','supplier'])test(kind+' legacy credit blocks invoice rename including cancelled and unresolved references',async()=>{
 const d=await fixture(kind),table=kind==='customer'?'fatture_cliente':'fatture_fornitore',notes=kind==='customer'?'note_credito':'note_credito_fornitore',key=kind==='customer'?'cliente_id':'fornitore_id';
 const invoice=(await db.query(`select num from ${table} where id=$1`,[d.fattura_id])).rows[0];
 const extra=kind==='customer'?{ftIds:[invoice.num,'UNRESOLVED'],annullato:true}:{ftfId:invoice.num,annullato:true};
 await db.query(`insert into ${notes}(company_id,num,data,${key},righe,extra) values($1,$2,$3,$4,$5,$6)`,[companies.A,'LEGACY-'+id(),'2026-09-19',d[key],JSON.stringify(d.righe),JSON.stringify(extra)]);
 await assert.rejects(asRole(db,'authenticated',users.admin,tx=>tx.query(`update ${table} set num=$1 where id=$2`,['RENAMED-'+id(),d.fattura_id])),/riferimenti legacy/);
 const free=await fixture(kind);await asRole(db,'authenticated',users.admin,tx=>tx.query(`update ${table} set num=$1 where id=$2`,['FREE-'+id(),free.fattura_id]));
 const linked=await fixture(kind);await save(linked,null,kind);await asRole(db,'authenticated',users.admin,tx=>tx.query(`update ${table} set num=$1 where id=$2`,['UUID-'+id(),linked.fattura_id]));
});
