const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const vm=require('node:vm');
const html=fs.readFileSync(path.join(__dirname,'../web/fatture.html'),'utf8');
function between(a,b){const start=html.indexOf(a),end=html.indexOf(b,start+a.length);assert.ok(start>=0&&end>start);return html.slice(start,end);}
const save=between("  $('f-save').addEventListener('click'",'  // Si parte SEMPRE');
function fixture(failure){let handler;const calls=[],messages=[];const fields=Object.fromEntries(Object.entries({'f-cliente':'C','f-ordine':'O','f-ddt':'D','f-dest':'','f-data':'2026-09-19','f-num':'FT/2026/0001'}).map(([k,value])=>[k,{value}]));fields['f-save']={addEventListener:(e,h)=>handler=h};
const ctx={$:id=>fields[id],editingId:null,editingFattura:null,numberPreview:'FT/2026/0001',companyId:'TENANT',allDdtById:{D:{id:'D'}},allOrdiniById:{O:{id:'O'}},readRighe:()=>[{cod:'A',qty:2,source_ddt_index:0}],setMsg:(m)=>messages.push(m),closeForm:()=>calls.push('close'),renderList:async()=>calls.push('render'),store:{checkDocLimit:async()=>({ok:true}),createCustomerInvoice:async(c,d,doc)=>{calls.push({c,d,doc});if(failure)throw Error('missing migration');return {fattura:{},ddt:{id:'D',ftId:'FT'},ordine:{id:'O',ftId:'FT'}};},saveDoc:()=>assert.fail('direct save'),bumpCounterPast:()=>assert.fail('separate counter'),nextNumber:()=>assert.fail('separate number')}};
vm.runInNewContext(save,ctx);return {handler,calls,messages,ctx};}
test('actual invoice form creates linked invoice by RPC without separate counter/writes',async()=>{const f=fixture();await f.handler();assert.equal(f.calls[0].doc.num,null);assert.equal(f.calls[0].doc.righe[0].source_ddt_index,0);assert.equal(f.ctx.allDdtById.D.ftId,'FT');assert.deepEqual(f.calls.slice(1),['close','render']);});
test('actual invoice form shows RPC failure and keeps caches without fallback',async()=>{const f=fixture(true);await f.handler();assert.equal(f.calls.length,1);assert.equal(f.ctx.allDdtById.D.ftId,undefined);assert.equal(f.messages.at(-1),'missing migration');});
