const {test,before,after}=require('node:test');const assert=require('node:assert/strict');const {database,seedTenants,asRole,uuid}=require('./helpers/database.cjs');let db,users,companies,n=90000;const client=uuid(90001),supplier=uuid(90002);
before(async()=>{db=await database(36);({users,companies}=await seedTenants(db));await db.query('insert into clienti(id,company_id,nome) values($1,$2,$3)',[client,companies.A,'Manual']);await db.query('insert into fornitori(id,company_id,nome) values($1,$2,$3)',[supplier,companies.A,'Manual']);});after(async()=>{if(db)await db.close();});
async function order(kind='customer',rows=[{cod:'A',qty:10,qtyEv:3},{cod:'A',qty:2,qtyEv:4}]){const t=kind==='customer'?'ordini_cliente':'ordini_fornitore',col=kind==='customer'?'cliente_id':'fornitore_id';return(await db.query(`insert into ${t}(company_id,num,data,${col},righe) values($1,$2,'2026-09-19',$3,$4) returning *`,[companies.A,'MAN'+(++n),kind==='customer'?client:supplier,JSON.stringify(rows)])).rows[0];}
async function call(o,kind='customer',key=uuid(++n),user=users.admin,rows=o.righe){return(await asRole(db,'authenticated',user,tx=>tx.query('select complete_order_manually($1,$2,$3,$4,$5,$6) r',[companies.A,kind,o.id,key,JSON.stringify(rows),'Consegna storica confermata']))).rows[0].r;}
for(const kind of ['customer','supplier'])test(kind+' monotonic completion preserves duplicate rows, replay and stale detection',async()=>{const o=await order(kind),key=uuid(++n);const r=await call(o,kind,key);assert.deepEqual(r.righe.map(r=>r.qtyEv),[10,4]);assert.deepEqual(await call(o,kind,key),r);await assert.rejects(call(o,kind),/modificato/);await assert.rejects(call(o,kind,key,users.admin,r.righe),/già utilizzato/);assert.equal((await db.query('select count(*) n from manual_order_completions where order_id=$1',[o.id])).rows[0].n,1);});
test('viewer, other tenant and anonymous cannot complete; operator can',async()=>{const o=await order();for(const u of [users.viewer,users.otherAdmin])await assert.rejects(call(o,'customer',uuid(++n),u),/autorizzata/);await assert.rejects(asRole(db,'anon',null,tx=>tx.query('select complete_order_manually($1,$2,$3,$4,$5,$6)',[companies.A,'customer',o.id,uuid(++n),JSON.stringify(o.righe),'reason'])),/permission/);assert.equal((await call(o,'customer',uuid(++n),users.operator)).righe[0].qtyEv,10);await assert.rejects(asRole(db,'authenticated',users.admin,tx=>tx.query('select * from manual_order_completions')),/permission/);});
test('audit failure rolls back fulfillment',async()=>{const o=await order();await db.exec("create function fail_manual() returns trigger language plpgsql as $$begin raise exception 'audit failure';end$$;create trigger fail_manual before insert on manual_order_completions for each row execute function fail_manual();");try{await assert.rejects(call(o),/audit failure/);assert.deepEqual((await db.query('select righe from ordini_cliente where id=$1',[o.id])).rows[0].righe,o.righe);}finally{await db.exec('drop trigger fail_manual on manual_order_completions;drop function fail_manual();');}});
test('tracked DDT cancellation removes only its contribution after manual completion',async()=>{const o=await order('customer',[{cod:'A',qty:10,qtyEv:0}]);const created=(await asRole(db,'authenticated',users.admin,tx=>tx.query('select create_customer_ddt($1,$2,$3,$4,$5) r',[companies.A,o.id,uuid(++n),JSON.stringify(o.righe),JSON.stringify({data:'2026-09-19',cliente_id:client,righe:[{cod:'A',qty:3,source_order_index:0}]})]))).rows[0].r;const current=(await db.query('select * from ordini_cliente where id=$1',[o.id])).rows[0];await call(current);const d=created.ddt;const expected=Object.fromEntries(['num','data','cliente_id','oc_id','dest_id','righe','extra'].map(k=>[k,d[k]]));await asRole(db,'authenticated',users.admin,tx=>tx.query('select change_customer_ddt($1,$2,$3,$4,$5,$6,$7)',[companies.A,d.id,uuid(++n),'cancel',JSON.stringify(expected),'{}','Documento errato']));assert.equal((await db.query('select righe from ordini_cliente where id=$1',[o.id])).rows[0].righe[0].qtyEv,7);});

test('direct fulfillment mutations and forged inserts rejected; unchanged editor upsert allowed',async()=>{for(const kind of ['customer','supplier']){const o=await order(kind,[{cod:'A',qty:10,qtyEv:3},{cod:'B',qty:5,qtyEv:4}]),t=kind==='customer'?'ordini_cliente':'ordini_fornitore',col=kind==='customer'?'cliente_id':'fornitore_id';const write=rows=>asRole(db,'authenticated',users.admin,tx=>tx.query(`update ${t} set righe=$1 where id=$2`,[JSON.stringify(rows),o.id]));await assert.rejects(write([{...o.righe[0],qtyEv:10},o.righe[1]]),/protetta|consegnat|ricevut/);await assert.rejects(write([...o.righe].reverse()),/protetta|consegnat|ricevut/);await assert.rejects(write([]),/protetta|consegnat|ricevut/);await write(o.righe.map(r=>({...r,descr:'Updated'})));await asRole(db,'authenticated',users.admin,tx=>tx.query(`insert into ${t}(id,company_id,num,data,${col},righe) values($1,$2,$3,$4,$5,$6) on conflict(id) do update set righe=excluded.righe`,[o.id,companies.A,o.num,'2026-09-19',kind==='customer'?client:supplier,JSON.stringify(o.righe)]));await assert.rejects(asRole(db,'authenticated',users.admin,tx=>tx.query(`insert into ${t}(company_id,num,data,${col},righe) values($1,$2,$3,$4,$5)`,[companies.A,'FORGE'+(++n),'2026-09-19',kind==='customer'?client:supplier,JSON.stringify(o.righe)])),/protetta|consegnat|ricevut/);}});


